### ISSUE TITLE
Req. #11 - Depending on how PS / Daemon interfaces to clients, determine whether or not local IPC can be used

### ISSUE THREAD

**Issue by amacgillivray** [amacgillivray/linear_algebra_accelerator#44]
**Description:** Determine whether or not local IPC can be used for Daemon requests or if messages must be sent over the internet (INET sockets). May need to rewrite to move to alternate method / abandon local solutions (#20)
**Artifact:** The answer will be provided in the end-of-sprint release notes, which will be provided to the GTA, and in the artifact(s) from issue 12. Laa::Daemon methods for the IPC methods we choose not to support will be removed (that is, either the mqueue support methods or the socket support methods).
**Story Points:** 3

**Comment by Andal01** [comment]
We have decided messages will be sent over INET sockets.
